=== baobabsoluciones/hackathonbaobab2021/hackathonbaobab2021/schemas/instance.json
{
    "$schema": "http://json-schema.org/schema#",
    "properties": {
        "BR2": {
            "items": {
                "properties": {
                    "_cat": {
                        "type": "string"
                    },
                    "_id": {
                        "type": "integer"
                    },
                    "homeMode": {
                        "type": "string"
                    },
                    "intp": {
                        "type": "string"
                    },
                    "mode2": {
                        "type": "string"
                    },
                    "penalty": {
                        "type": "string"
                    },
                    "slots": {
                        "type": "string"
                    },
                    "teams": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string"
                    }
                },
                "required": [
                    "_cat",
                    "_id",
                    "homeMode",
                    "intp",
                    "mode2",
                    "penalty",
                    "slots",
                    "teams",
                    "type"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "CA1": {
            "items": {
                "properties": {
                    "_cat": {
                        "type": "string"
                    },
                    "_id": {
                        "type": "integer"
                    },
                    "max": {
                        "type": "string"
                    },
                    "min": {
                        "type": "string"
                    },
                    "mode": {
                        "type": "string"
                    },
                    "penalty": {
                        "type": "string"
                    },
                    "slots": {
                        "type": "string"
                    },
                    "teams": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string"
                    }
                },
                "required": [
                    "_cat",
                    "_id",
                    "max",
                    "min",
                    "mode",
                    "penalty",
                    "slots",
                    "teams",
                    "type"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "CA3": {
            "items": {
                "properties": {
                    "_cat": {
                        "type": "string"
                    },
                    "_id": {
                        "type": "integer"
                    },
                    "intp": {
                        "type": "string"
                    },
                    "max": {
                        "type": "string"
                    },
                    "min": {
                        "type": "string"
                    },
                    "mode1": {
                        "type": "string"
                    },
                    "mode2": {
                        "type": "string"
                    },
                    "penalty": {
                        "type": "string"
                    },
                    "teams1": {
                        "type": "string"
                    },
                    "teams2": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string"
                    }
                },
                "required": [
                    "_cat",
                    "_id",
                    "intp",
                    "max",
                    "min",
                    "mode1",
                    "mode2",
                    "penalty",
                    "teams1",
                    "teams2",
                    "type"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "GA1": {
            "items": {
                "properties": {
                    "_cat": {
                        "type": "string"
                    },
                    "_id": {
                        "type": "integer"
                    },
                    "max": {
                        "type": "string"
                    },
                    "meetings": {
                        "type": "string"
                    },
                    "min": {
                        "type": "string"
                    },
                    "penalty": {
                        "type": "string"
                    },
                    "slots": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string"
                    }
                },
                "required": [
                    "_cat",
                    "_id",
                    "max",
                    "meetings",
                    "min",
                    "penalty",
                    "slots",
                    "type"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "SE1": {
            "items": {
                "properties": {
                    "_cat": {
                        "type": "string"
                    },
                    "_id": {
                        "type": "integer"
                    },
                    "min": {
                        "type": "string"
                    },
                    "mode1": {
                        "type": "string"
                    },
                    "penalty": {
                        "type": "string"
                    },
                    "teams": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string"
                    }
                },
                "required": [
                    "_cat",
                    "_id",
                    "min",
                    "mode1",
                    "penalty",
                    "teams",
                    "type"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "leagues": {
            "items": {
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "id",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "slots": {
            "items": {
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "id",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        },
        "teams": {
            "items": {
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "league": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "id",
                    "league",
                    "name"
                ],
                "type": "object"
            },
            "type": "array"
        }
    },
    "required": [
        "BR2",
        "CA1",
        "CA3",
        "GA1",
        "SE1",
        "leagues",
        "slots",
        "teams"
    ],
    "type": "object"
}

=== baobabsoluciones/hackathonbaobab2021/hackathonbaobab2021/data/example_instance.json
{
    "BR2": [],
    "CA1": [],
    "CA3": [],
    "GA1": [],
    "SE1": [
        {
            "_cat": "SE1",
            "_id": 0,
            "min": "1",
            "mode1": "SLOTS",
            "penalty": "10",
            "teams": "0;1;2;3",
            "type": "SOFT"
        }
    ],
    "leagues": [
        {
            "id": "0",
            "name": "League 0"
        }
    ],
    "slots": [
        {
            "id": "0",
            "name": "Slot 0"
        },
        {
            "id": "1",
            "name": "Slot 1"
        },
        {
            "id": "2",
            "name": "Slot 2"
        },
        {
            "id": "3",
            "name": "Slot 3"
        },
        {
            "id": "4",
            "name": "Slot 4"
        },
        {
            "id": "5",
            "name": "Slot 5"
        }
    ],
    "teams": [
        {
            "id": "0",
            "league": "0",
            "name": "Team 0"
        },
        {
            "id": "1",
            "league": "0",
            "name": "Team 1"
        },
        {
            "id": "2",
            "league": "0",
            "name": "Team 2"
        },
        {
            "id": "3",
            "league": "0",
            "name": "Team 3"
        }
    ]
}
